[workspace]
resolver = "2"

members = ["pika-proxy", "redis"]

[workspace.dependencies]
tokio = { version = "1.28", features = [
    "rt-multi-thread",
    "macros",
    "sync",
    "net",
] }
tracing = "0.1.37"
